# https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/spec/index.html#structs
[build]
target = "x86_64-unknown-none"
#rustflags = ["-C", "link-args=--script=linker.ld"]
#rustflags = [ "-C", "target-cpu=native" ]
rustflags = [ "-C", "link-args=--image-base=0x200000" ]

# Make cargo run automatically start qemu
[target.'cfg(target_os = "none")']
runner = "glue_gun run"
