# https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/spec/index.html#structs
[build]
target = "x86_64-unknown-none"
#rustflags = [ "-C", "target-cpu=native" ]

# Make cargo run automatically start qemu
[target.'cfg(target_os = "none")']
runner = "glue_gun run"
