[package]
name = "bootloader"
version = "0.1.0"
authors = ["Luis Hebendanz <luis.nixos@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uart_16550 = { path = "../uart_16550"  }
bitflags = "1.3.2"

[target.'cfg(target_arch = "x86")'.dependencies]
x86 = { path = "../x86", features=["instructions"]  }
log = {version = "0.4.11", features = ["release_max_level_trace"] }
multiboot2 = "0.12.2"

[build-dependencies]
llvm-tools = { version = "0.1" }

[features]
binary = []


[package.metadata.bootloader]
target = "i686-unknown-linux-gnu.json"
build-std = "core"

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
lto = false
debug = false
